version: '3.8'
services:
  # Kafka broker (using Redpanda)
  redpanda:
    image: redpandadata/redpanda:latest
    command:
      - redpanda start --overprovisioned --smp 1 --memory 512M --reserve-memory 0M
    ports:
      - "9092:9092"
    networks:
      - appnet

  # Producer Service
  result-service:
    build: ./result-service
    depends_on:
      - redpanda
    ports:
      - "8081:8080"
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=redpanda:9092
    networks:
      - appnet

  # Consumer Service
  result-worker-service:
    build: ./result-worker-service
    depends_on:
      - redpanda
    ports:
      - "8082:8080"
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=redpanda:9092
    networks:
      - appnet

networks:
  appnet:
